name: Linux packager

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*"
      - "*.*.*"

jobs:
  builder:
    name: Linux package builder
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Run Docker Compose
      working-directory: build/package
      run: docker compose -f arch/compose.yml -f deb/compose.yml -f rpm/compose.yml up
    - name: Test Arch Linux package
      run: |
        docker run --rm -v ./build/package/release:/release:ro archlinux:latest sh -c '
          pacman -Sy --noconfirm && \
          pacman -U --noconfirm /release/*.pkg.tar.zst && \
          wikiman -h | grep -q "^Options"'
    - name: Test Ubuntu package
      run: |
        docker run --rm -v ./build/package/release:/release:ro ubuntu:latest sh -c '
          apt update && \
          apt -y install /release/*.deb && \
          wikiman -h | grep -q "^Options"'
    - name: Test Fedora package
      run: |
        docker run --rm -v ./build/package/release:/release:ro fedora:latest sh -c '
          dnf install -y /release/*.rpm && \
          wikiman -h | grep -q "^Options"'
    - name: Upload packages to a new draft release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: v${{ github.ref }}
        tag_name: ${{ github.ref }}
        files: ./build/package/release/*
        draft: true
        fail_on_unmatched_files: true
        generate_release_notes: true
